### ISSUE TITLE
Failed to run demo.sh due to a compilation error in the miniscript package.

### ISSUE THREAD

**Issue by kannapoix** [RGB-Tools/rgb-sandbox#2]
# What went wrong
Running `bash demo.sh` results in an error, failing to compile bdk-cli. 
The root cause is the miniscript package, on which bdk-cli indirectly depends.

rgb-sandbox version: v0.10 or the commit https://github.com/RGB-Tools/rgb-sandbox/commit/d2707b9aa0e484eca8e05b6f9bbabba0b957936c.

To work around this issue, set `BDK_CLI_VER="0.26.0"` in `demo.sh`. This will complete the script, but it is uncertain whether the demo will work correctly.

# Details
The exact error is as follows:

```rust
error[E0275]: overflow evaluating the requirement `F: FnMut<(&Pk,)>`
  |
  = help: consider increasing the recursion limit by adding a `#![recursion_limit = "256"]` attribute to your crate (`miniscript`)
  = note: required for `&mut F` to implement `FnMut<(&Pk,)>`
  = note: 128 redundant requirements hidden
  = note: required for `&mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut ...` to implement `FnMut<(&Pk,)>`
  = note: the full type name has been written to '/tmp/cargo-installldSIZU/release/deps/miniscript-4331abc3e75b540d.long-type-2030699453202166277.txt'

For more information about this error, try `rustc --explain E0275`.
error: could not compile `miniscript` (lib) due to previous error
warning: build failed, waiting for other jobs to finish...
error: failed to compile `bdk-cli v0.27.1`, intermediate artifacts can be found at `/tmp/cargo-installldSIZU`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.

ERROR: error installing bdk-cli
```

This is a known issue already reported in the miniscript repo.
https://github.com/rust-bitcoin/rust-miniscript/issues/549

Miniscript [v9.0.2](https://github.com/rust-bitcoin/rust-miniscript/blob/9.0.2/CHANGELOG.md) fixes this issue. 
However, bdk-cli v0.27.1, which is used by rgb-sandbox, depends on bdk v0.27.1, which in turn relies on miniscript v9.0.

https://github.com/RGB-Tools/rgb-lib/issues/27 is related issue.

**Comment by nicbus** [comment]
Unfortunately `bdk-cli`'s latest version is still `0.27.1`, so I worked around this by installing `bdk-cli` in debug mode.

This is available in the updated master branch (commit `2f4e2ba`) so closing this, feel free to re-open if needed.
