### ISSUE TITLE
ERROR: not enough PSBT output found to put all required state (can't add assignment type 4000 for unspecified-velocity state).

### ISSUE THREAD

**Issue by cymqqqq** [RGB-Tools/rgb-sandbox#4]
Hi there, when I test my rgb20 code, I executed my shell code:
CLOSING_METHOD="opret1st"
DERIVE_PATH="m/86'/1'/0'/9"
DESC_TYPE="wpkh"
ELECTRUM="blockstream.info:110"
# "localhost:50001"
CONSIGNMENT="consignment.rgb"
PSBT="tx.psbt"
IFACE="RGB20"
rgb0() {
    program -n bitcoin rgb -d data0 -s "$ELECTRUM" $@
}

rgb0 transfer --method "$CLOSING_METHOD" ./tx.psbt "$invoice" "data0/$CONSIGNMENT"
For this transfer code, the errors prints out:
ERROR: not enough PSBT output found to put all required state (can't add assignment type 4000 for unspecified-velocity state).
So the reason is?

**Comment by cymqqqq** [comment]
enough satoshi or other reasons?

**Comment by 22388o** [comment]
>not enough PSBT output found to put all required state (can't add assignment type 4000 for unspecified-velocity state).

There no PSBT output enough for RGB20 token or type 4000 is incorrect

**Comment by pocolocosv** [comment]
It seems you are not following the documented manual demo (e.g. `ELECTRUM="blockstream.info:110"`), so in order to be able to help, the complete list of commands is required. Please post the full commands you used so we can better understand your situation.
You might also be using a customized version of the project. If so, please share your changes so we can help understand what went wrong.

**Comment by cymqqqq** [comment]
For ELECTRUM="blockstream.info:110", I tested with the bitcoin mainnet, but it can not run completely. For ELECTRUM="localhost:50001", I have tested with the regtest, and it worked.
Here is all my shell code:
CLOSING_METHOD="opret1st"
DERIVE_PATH="m/86'/1'/0'/9"
DESC_TYPE="wpkh"
ELECTRUM="blockstream.info:110"
CONSIGNMENT="consignment.rgb"
PSBT="tx.psbt"
IFACE="RGB20"

program() {
    issue-rgb20-token $@
}
rgb0() {
    program -n bitcoin rgb -d data0 -s "$ELECTRUM" $@
}
rgb1() {
    program -n bitcoin rgb -d data1 -s "$ELECTRUM" $@
}

trap cleanup EXIT


sleep 1

echo "======== Prepare wallets"

## Prepare issuer wallet
xprv_0=$(program -n bitcoin key generate | jq -r '.xprv')
output=$(program -n bitcoin key derive -p "$DERIVE_PATH" -x "$xprv_0")
xprv_der_0=$(echo $output | jq -r '.xprv')
xpub_der_0=$(echo $output | jq -r '.xpub')

## Prepare users(receivers) wallets
# receiver-1
xprv_1=$(program -n bitcoin key generate | jq -r '.xprv')
output=$(program -n bitcoin key derive -p "$DERIVE_PATH" -x "$xprv_1")
xprv_der_1=$(echo $output | jq -r '.xprv')
xpub_der_1=$(echo $output | jq -r '.xpub')

echo "======== Generate address"

# issuer
addr_issue=$(program -n bitcoin wallet -w issuer -d "$DESC_TYPE($xpub_der_0)" get-new-address | jq -r '.address')
addr_issue_change=$(program -n bitcoin wallet -w issuer -d "$DESC_TYPE($xpub_der_0)" get-new-address | jq -r '.address')
# receiver1

addr_receive1=$(program -n bitcoin wallet -w receiver1 -d "$DESC_TYPE($xpub_der_1)" get-new-address | jq -r '.address')
addr_receive1_fee=$(program -n bitcoin wallet -w receiver1 -d "$DESC_TYPE($xpub_der_1)" get-new-address | jq -r '.address')
 addr_receive1_change=$(program -n bitcoin wallet -w receiver1 -d "$DESC_TYPE($xpub_der_1)" get-new-address | jq -r '.address')

echo "======== Sync and setup outpoints"

program -n bitcoin wallet -w issuer -d "$DESC_TYPE($xpub_der_0)" -s "$ELECTRUM" sync
program -n bitcoin wallet -w receiver1 -d "$DESC_TYPE($xpub_der_1)" -s "$ELECTRUM" sync

program -n bitcoin wallet -w issuer -d "$DESC_TYPE($xpub_der_0)" list-unspent
program -n bitcoin wallet -w receiver1 -d "$DESC_TYPE($xpub_der_1)" list-unspent

outpoint_issue=$(program -n bitcoin wallet -w issuer -d "$DESC_TYPE($xpub_der_0)" list-unspent | jq -r '.[0].outpoint')
outpoint_receive1=$(program -n bitcoin wallet -w receiver1 -d "$DESC_TYPE($xpub_der_1)" list-unspent | jq -r '.[0].outpoint')
outpoint_receive1_fee=$(program -n bitcoin wallet -w receiver1 -d "$DESC_TYPE($xpub_der_1)" list-unspent | jq -r '.[1].outpoint')
echo "======== Setup contracts"

rgb0 import rgb-schemata/NonInflatableAssets.rgb
rgb0 import rgb-schemata/NonInflatableAssets-RGB20.rgb
rgb1 import rgb-schemata/NonInflatableAssets.rgb
rgb1 import rgb-schemata/NonInflatableAssets-RGB20.rgb

schema=$(rgb0 schemata | awk '{print $1}')
sed \
    -e "s/issued_supply/1000/" \
    -e "s/created_timestamp/$(date +%s)/" \
    -e "s/closing_method/$CLOSING_METHOD/" \
    -e "s/txid:vout/$outpoint_issue/" \
    contracts/usdt.yaml.template > contracts/usdt.yaml
issuance="$(rgb0 issue "$schema" "$IFACE" contracts/usdt.yaml 2>&1)"
echo "issuance: $issuance"
contract_id="$(echo "$issuance" | grep '^A new contract' | cut -d' ' -f4)"
echo "contract_id: $contract_id"
rgb0 contracts
rgb0 state "$contract_id" "$IFACE"

echo "======== Start special transfer (from issuer to receiver1)"

invoice=$(rgb1 invoice "$contract_id" "$IFACE" 60 "$CLOSING_METHOD:$outpoint_receive1")
echo "invoice : $invoice"
echo "$DESC_TYPE($xpub_der_1)"
echo $outpoint_receive1_fee
echo $addr_receive1_change
program -n bitcoin \
        wallet -w receiver1 -d "$DESC_TYPE($xpub_der_1)" \
        init-payfee-psbt -f 5 --input $outpoint_receive1_fee --to $addr_receive1_change:0 --psbt ./tx.psbt

echo "$DESC_TYPE($xpub_der_0)"
echo $outpoint_issue
program -n bitcoin \
        wallet -w issuer -d "$DESC_TYPE($xpub_der_0)" \
        add-sender-input -f 5 --input $outpoint_issue --psbt ./tx.psbt

rgb0 set-host --method "$CLOSING_METHOD" ./tx.psbt
rgb0 transfer --method "$CLOSING_METHOD" ./tx.psbt "$invoice" "data0/$CONSIGNMENT"

cp data{0,1}/"$CONSIGNMENT"
rgb1 validate "data1/$CONSIGNMENT"

program -n bitcoin wallet -w issuer -d "$DESC_TYPE($xprv_der_0)" sign --psbt ./tx.psbt

**Comment by pocolocosv** [comment]
This project only works in regtest. It is not meant to be used in mainnet and it will likely always fail. See the  answer in the `RGB-WG/rgb`’s [issue #98](https://github.com/orgs/RGB-WG/discussions/98)  that you posted for more info.

**Comment by cymqqqq** [comment]
So how can we make it work in mainnet? (Any solutions?)
